language: node_js
node_js:
  - "node"

cache: npm

script: npm run build

dist: focal

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: main

env:
  - NODE_OPTIONS=--openssl-legacy-provider